M48
; DRILL file KiCad 10.0.6 date 2026-10-10T12:04:26
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-10-10T12:04:26-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.600
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.500
%
G90
G05
T1
X111.488Y-41.948
T2
X130.2Y-157.6
X162.4Y-157.6
M30
